name: Autograding Tests
'on':
- workflow_dispatch
- repository_dispatch
permissions:
  checks: write
  actions: read
  contents: read
jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: m01&#45;01&#45;01
      id: m01-45-01-45-01
      uses: classroom-resources/autograding-io-grader@v1
      with:
        test-name: m01&#45;01&#45;01
        setup-command: make compile
        command: make -s test_01
        input: |
          create-account#Wiro Sableng#wirsab
          create-account#Jaka Sembung#jaksem
          create-transaction#jaksem#15.0#2023/02/14 14:14:14#Weekly income
          create-transaction#jaksem#-8.4#2023/02/15 15:18:15#SIM credit
          create-transaction#jaksem#37.1#2023/02/15 15:15:15#Book refund
          create-transaction#wirsab#-5.0#2023/02/16 10:15:41#Tax
          show-account#jaksem
          show-account#wirsab
          ---
        expected-output: |
          wirsab|Wiro Sableng|0.0
          jaksem|Jaka Sembung|0.0
          jaksem|Jaka Sembung|43.7
          1|jaksem|15.0|2023/02/14 14:14:14|Weekly income
          3|jaksem|37.1|2023/02/15 15:15:15|Book refund
          2|jaksem|-8.4|2023/02/15 15:18:15|SIM credit
          wirsab|Wiro Sableng|0.0
        comparison-method: exact
        timeout: 1
        max-score: 25
    - name: m01&#45;01&#45;02
      id: m01-45-01-45-02
      uses: classroom-resources/autograding-io-grader@v1
      with:
        test-name: m01&#45;01&#45;02
        setup-command: make compile
        command: make -s test_01
        input: |
          create-account#Wiro Sableng#wirsab
          create-account#Jaka Sembung#jaksem
          create-transaction#jaksem#-8.4#2023/02/15 15:18:15#SIM credit
          create-transaction#jaksem#37.1#2023/02/15 15:15:15#Book refund
          create-transaction#wirsab#-5.0#2023/02/16 10:15:41#Tax
          create-account#Milkyman#milkyn
          create-transaction#jaksem#15.0#2023/02/14 14:14:14#Weekly income
          create-transaction#milkyn#100.00#2023/03/11 08:00:40#Research grant (March)
          create-transaction#milkyn#8.56#2023/03/11 08:00:20#Assistancy paycheck
          show-accounts
          ---
        expected-output: |
          wirsab|Wiro Sableng|0.0
          jaksem|Jaka Sembung|0.0
          milkyn|Milkyman|0.0
          jaksem|Jaka Sembung|52.1
          2|jaksem|15.0|2023/02/14 14:14:14|Weekly income
          1|jaksem|37.1|2023/02/15 15:15:15|Book refund
          milkyn|Milkyman|108.56
          4|milkyn|8.56|2023/03/11 08:00:20|Assistancy paycheck
          3|milkyn|100.0|2023/03/11 08:00:40|Research grant (March)
          wirsab|Wiro Sableng|0.0
        comparison-method: exact
        timeout: 1
        max-score: 25
    - name: m01&#45;01&#45;03
      id: m01-45-01-45-03
      uses: classroom-resources/autograding-io-grader@v1
      with:
        test-name: m01&#45;01&#45;03
        setup-command: make compile
        command: make -s test_01
        input: |
          create-account#Wiro Sableng#wirsab
          create-account#Jaka Sembung#jaksem
          create-transaction#jaksem#-8.4#2023/02/15 15:18:15#SIM credit
          create-transaction#jaksem#37.1#2023/02/15 15:15:15#Book refund
          create-transaction#wirsab#-5.0#2023/02/16 10:15:41#Tax
          create-account#Milkyman#milkyn
          create-transaction#jaksem#15.0#2023/02/14 14:14:14#Weekly income
          create-transaction#milkyn#100.00#2023/03/11 08:00:40#Research grant (March)
          create-transaction#milkyn#8.56#2023/03/11 08:00:20#Assistancy paycheck
          remove-account#jaksem
          show-accounts
          ---
        expected-output: |
          wirsab|Wiro Sableng|0.0
          jaksem|Jaka Sembung|0.0
          milkyn|Milkyman|0.0
          milkyn|Milkyman|108.56
          4|milkyn|8.56|2023/03/11 08:00:20|Assistancy paycheck
          3|milkyn|100.0|2023/03/11 08:00:40|Research grant (March)
          wirsab|Wiro Sableng|0.0
        comparison-method: exact
        timeout: 1
        max-score: 25
    - name: m01&#45;01&#45;04
      id: m01-45-01-45-04
      uses: classroom-resources/autograding-io-grader@v1
      with:
        test-name: m01&#45;01&#45;04
        setup-command: make compile
        command: make -s test_01
        input: |
          create-account#Wiro Sableng#wirsab
          create-account#Milkyman#milkyn
          create-account#Jaka Sembung#jaksem
          create-transaction#jaksem#37.1#2023/02/15 15:15:15#Book refund
          create-transaction#wirsab#-5.0#2023/02/16 10:15:41#Tax
          create-transaction#jaksem#-8.4#2023/02/15 15:12:15#SIM credit
          remove-account#wirsab
          create-transaction#milkyn#100.00#2023/03/11 08:00:40#Research grant (March)
          create-transaction#jaksem#15.0#2023/02/14 14:14:14#Weekly income
          create-transaction#milkyn#8.56#2023/03/11 08:00:20#Assistancy paycheck
          show-accounts
          ---
        expected-output: |
          wirsab|Wiro Sableng|0.0
          milkyn|Milkyman|0.0
          jaksem|Jaka Sembung|0.0
          jaksem|Jaka Sembung|43.7
          4|jaksem|15.0|2023/02/14 14:14:14|Weekly income
          2|jaksem|-8.4|2023/02/15 15:12:15|SIM credit
          1|jaksem|37.1|2023/02/15 15:15:15|Book refund
          milkyn|Milkyman|108.56
          5|milkyn|8.56|2023/03/11 08:00:20|Assistancy paycheck
          3|milkyn|100.0|2023/03/11 08:00:40|Research grant (March)
        comparison-method: exact
        timeout: 1
        max-score: 25
    - name: Autograding Reporter
      uses: classroom-resources/autograding-grading-reporter@v1
      env:
        M01-45-01-45-01_RESULTS: "${{steps.m01-45-01-45-01.outputs.result}}"
        M01-45-01-45-02_RESULTS: "${{steps.m01-45-01-45-02.outputs.result}}"
        M01-45-01-45-03_RESULTS: "${{steps.m01-45-01-45-03.outputs.result}}"
        M01-45-01-45-04_RESULTS: "${{steps.m01-45-01-45-04.outputs.result}}"
      with:
        runners: m01-45-01-45-01,m01-45-01-45-02,m01-45-01-45-03,m01-45-01-45-04
